---
- hosts: all
  become: True
  ignore_errors: True
  tasks:
  
   - name: Make sure a service unit is stop
     service:
       name: cloudblm-asset-service
       state: stopped

   - name: Make sure a service unit is restart
     service:
       name: cloudblm-asset-service
       state: restarted